import {StyleSheet} from 'react-native';
import {Colors, Metrics, Fonts} from '../../theme';

export default StyleSheet.create({
  imageView: {
    backgroundColor: Colors.White,
    marginHorizontal: Metrics.ratio(14),
    borderRadius: Metrics.ratio(10),
    paddingBottom: Metrics.ratio(15),
    marginTop: Metrics.ratio(15),
  },
  buyBtn: {
    backgroundColor: Colors.Affair,
    borderRadius: Metrics.ratio(20),
    paddingVertical: Metrics.ratio(7),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Metrics.ratio(15),
    width: Metrics.ratio(120),
    flexDirection: 'row',
  },
  uploadBtn: {
    backgroundColor: Colors.Affair,
    borderRadius: Metrics.ratio(20),
    paddingVertical: Metrics.ratio(7),
    paddingLeft: Metrics.ratio(15),
    paddingRight: Metrics.ratio(15),
    justifyContent: 'center',
    alignItems: 'center',
    width: Metrics.ratio(120),
    flexDirection: 'row',
    marginTop: Metrics.ratio(15),
  },
  ImageUserView: {
    backgroundColor: Colors.Affair,
    borderRadius: Metrics.screenHeight * 0.018,
    height: Metrics.screenHeight * 0.113,
    width: Metrics.screenHeight * 0.113,
    borderWidth: Metrics.ratio(1),
    borderColor: Colors.Mercury,
    overflow: 'hidden',
    marginTop: Metrics.ratio(10),
    marginHorizontal: Metrics.ratio(5),
  },
  image: {
    height: '100%',
    width: '100%',
  },
  imageDefault: {
    height: Metrics.screenHeight * 0.1,
    width: Metrics.screenHeight * 0.1,
  },
  BuyBtnText: {
    color: Colors.White,
    fontFamily: Fonts.type.NunitoBold,
    fontSize: Metrics.ratio(10),
    marginLeft: Metrics.ratio(10),
  },
  pickerView: {
    height: Metrics.ratio(45),
    marginRight: Metrics.ratio(20),
    marginTop: Metrics.ratio(4),
    justifyContent: 'center',
  },
  upload: {
    height: Metrics.ratio(12),
    width: Metrics.ratio(12),
  },
  picker_arrow: {
    height: Metrics.ratio(15),
    width: Metrics.ratio(15),
  },
  uploadArea: {
    paddingHorizontal: Metrics.ratio(15),
    justifyContent: 'space-between',
    marginBottom: Metrics.ratio(5),
    flexDirection: 'row',
  },
  titleTextInput: {
    backgroundColor: Colors.White,
    textAlignVertical: 'top',
    borderRadius: Metrics.ratio(16),
    padding: Metrics.ratio(20),
    paddingHorizontal: Metrics.ratio(20),
    fontSize: Metrics.ratio(14),
    fontFamily: Fonts.type.NunitoLight,
    color: Colors.Black,
    borderColor: Colors.Mercury,
    borderWidth: Metrics.ratio(1),
  },
  titleCount: {
    fontSize: Metrics.ratio(10),
    color: Colors.Charade,
    fontFamily: Fonts.type.Nunito,
    marginTop: Metrics.ratio(6),
    textAlign: 'right',
    marginRight: Metrics.ratio(20),
  },
  facebookIcon: {
    height: Metrics.ratio(15),
    width: Metrics.ratio(15),
  },
  pickerContainer: {
    marginBottom: Metrics.ratio(20),
  },
  fbTxt: {
    fontSize: Metrics.ratio(12),
    color: Colors.Charade,
    fontFamily: Fonts.type.Nunito,
    marginHorizontal: Metrics.ratio(10),
  },
  socialLinkArea: {
    flexDirection: 'row',
    marginTop: Metrics.ratio(5),
    marginBottom: Metrics.ratio(15),
  },
  purpleBtn: {
    backgroundColor: Colors.Affair,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Metrics.ratio(12),
    borderRadius: Metrics.ratio(30),
    width: Metrics.ratio(90),
    position: 'absolute',
    right: 0,
  },
  BtnText: {
    fontFamily: Fonts.type.NunitoBold,
    fontSize: Metrics.ratio(16),
    color: Colors.White,
  },
  tagArea: {
    borderColor: Colors.Mercury,
    borderWidth: 2,
    borderRadius: Metrics.ratio(30),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Metrics.ratio(15),
    marginBottom: Metrics.ratio(15),
    borderRightWidth: 0,
  },
  inputTag: {
    flex: 1,
    height: Metrics.ratio(40),
    borderTopLeftRadius: Metrics.ratio(30),
    borderBottomLeftRadius: Metrics.ratio(30),
    paddingHorizontal: Metrics.ratio(15),
  },
  errormsg: {
    color: 'red',
    fontSize: Fonts.size.fourteen,
    fontFamily: Fonts.type.Nunito,
    marginHorizontal: Metrics.ratio(15),
  },
  gradientButtonContainer: {
    marginTop: Metrics.ratio(25),
    marginBottom: Metrics.ratio(100),
  },
  labelTopText: {
    position: 'absolute',
    color: Colors.Affair,
    top: Metrics.ratio(4),
    left: Metrics.ratio(20),
    fontSize: Metrics.ratio(10),
    zIndex: Metrics.ratio(2),
  },
  close: {
    backgroundColor: Colors.White,
    justifyContent: 'center',
    alignItems: 'center',
    width: Metrics.screenHeight * 0.025,
    height: Metrics.screenHeight * 0.025,
    borderRadius: Metrics.ratio(30),
    position: 'absolute',
    right: Metrics.ratio(5),
    top: Metrics.ratio(5),
  },
  imgMainContainer: {
    paddingHorizontal: Metrics.ratio(10),
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  fieldsContainer: {
    marginTop: Metrics.ratio(10),
    paddingHorizontal: Metrics.ratio(15),
  },
  pickerSelectPlaceholder: {
    color: Colors.Mercury,
    fontFamily: Fonts.type.Nunito,
    fontSize: Metrics.ratio(13),
  },
  pickerSelectInputAndroid: {
    color: Colors.Black,
    fontSize: Metrics.ratio(13),
    fontFamily: Fonts.type.NunitoLight,
    borderColor: Colors.Mercury,
    borderWidth: 1,
    borderRadius: Metrics.ratio(30),
    paddingHorizontal: Metrics.ratio(20),
    textTransform: 'capitalize',
  },
});
